### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Dotenv\Dotenv::create()

### ISSUE THREAD

**Issue by axebelk** [stechstudio/laravel-bref-bridge#13]
I have got the above error while running: php artisan bref:config-sam

**Comment by V13Axel** [comment]
What version of Laravel and of this package are you running? 

`Dotenv::create()` is the way to create an instance of Dotenv as of Dotenv V3, used as of Laravel 5.8.
